### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by neuman** [jherico/OculusSDK#48]
New to Oculus on Linux, so I may be being foolish but...

I followed the instructions in README.Linux after checking out the official branch, first two commands went perfectly but "sudo make PREFIX=/opt/oculus install" yields:

install: cannot stat ‘Tools/RiftConfigUtil/Bin/Linux/x86_64/ReleaseStatic/RiftConfigUtil’: No such file or directory
make: *** [install] Error 1

**Comment by jherico** [comment]
The 'official' branch is essentially the same code you'd get from Oculus by downloading the SDK. If that's what you want to work with, and you're having problems with the installation, you report the problem on the official Oculus forums.  

Most likely the reason you're getting the error is that my Git repository contains *only* the code from the official SDK, but none of the binaries (such as the RiftConfigUtil).  

If on the other hand you want to use my version of the SDK, you should work from the master branch and ignore the build instructions from the readme.  

I use CMake as a meta-build tool, so building and installing would work like so:

```
mkdir build
cd build
cmake ..
make
sudo make install
```

I don't think it will install anywhere but to /usr/local/include & /usr/local/lib, because I've never done much work on customizability of the install targets.

If you're still having trouble building after this, please feel free to re-open this issue.
