### ISSUE TITLE
Output doesn't make an i386 binary

### ISSUE THREAD

**Issue by dakatk** [jherico/OculusSDK#50]
I followed the instruction in the README file, first running `make release` in the root directory of the downloaded file, which finished without errors. Then I proceeded to run `sudo make install`, and immediately I got an error saying `cannot stat ‘Service/OVRServer/Bin/Linux/i386/ReleaseStatic/ovrd’: No such file or directory`. I checked and sure enough, there had been no output to that directory. I even re-tried after deleting the 'x86_64' directory and making the 'i386/ReleaseStatic' directory. Still no 'ovrd' in that directory.

**Comment by jherico** [comment]
Bear in mind that this is not an official repository and that the readme and makefile you're using are authored by Oculus, so you're not going to get official help here.  However, I can shed some light on this.

`ovrd` is the Oculus Runtime binary, included in their Linux SDK distribution.  It's not an artifact of the build process.  Oculus only provides a 64 bit version of this runtime and does not provide the source code, so I can't build it.  

I'm assuming that you're attempting to build for a 32 bit OS, rather than trying to build a 32 bit version of the SDK on a 64 bit system.  Unfortunately there's no good solution for 32 bit Linux at this time until such time as Oculus either releases support for it, or someone produces a fully open source SDK for the Rift hardware.
